default: &default
  adapter: postgresql
  host: localhost

development:
  <<: *default
  database: rails_test_5_development

test:
  <<: *default
  database: rails_test_5_test

production:
  <<: *default
  database: rails_test_5_production